### PR TITLE
Ack support

### PR DESCRIPTION
**Pull request by tosan88**
Note: Needed to be merged before: https://github.com/Financial-Times/go-fthealth/pull/7 (build & tests will fail until then)

### CODE REVIEW

**Comment by tosan88** [comment]
Testing in xp: https://xp-up.ft.com/__health

**Comment by kovacshuni** [comment]
i'd change the words from acked warning to warning acked. And not write acked in all caps, everything is all caps now.
Also would omit acked details words. That would be the invisible header of that column that everyone could guess, the comment is fine.
Also would omit "see below details" in title. 
Word order again: acked 7 services should be 7 services acked.
Or rather just, don't change the title at all. It's a long title, should be concise.

**Comment by kovacshuni** [comment]
+1

**Comment by tamas-molnar** [comment]
+1

**Comment by BerniVarga** [comment]
+1

**Pull request merged**
